classname: salina_cl.algorithms.ppo.ppo
params:
  learning_device: cuda:0
  acquisition_device: cuda:0

  optimizer_policy:
    classname: torch.optim.Adam
    lr: 0.0003

  optimizer_critic:
    classname: torch.optim.Adam
    lr: 0.0003

  clip_grad: 10.0

  control_every_n_epochs: 10
  n_control_rollouts: 0
  n_timesteps: 50
  n_processes: 0
  n_minibatches: 64
  n_envs_per_minibatch: 512
  n_timesteps_per_minibatch: 10
  n_times_per_minibatch: 1

  discount_factor: 0.99
  clip_ratio: 0.2
  action_std: 0.4
  gae: 0.96
  reward_scaling: 1.0
  time_limit: 0