env_name: CustomHalfcheetah
wrapper_classname: salina_examples.rl.LoP.envs.create_gym_env
n_models: 2
save_every: 100
device : cuda:0

logger:
  classname: salina.logger.TFLogger
  log_dir: experiments/ensembling/${hydra:job.id}
  every_n_seconds: 10
  modulo: 1
  verbose: False

acquisition:
  seed: 0
  n_envs: 2048
  n_timesteps: 20
  env:
    env_name: ${env_name}
    episode_length: 1000
    env_spec:
      torso: 1.
      thig: 1.
      shin: 1
      foot: 1.
      gravity: 1.
      friction: 1.

validation:
  seed: 1
  n_envs: 128
  evaluate_every: 10
  env:
    env_name: ${env_name}
    episode_length: 1000
    env_spec:
      torso: 1.
      thig: 1.
      shin: 1
      foot: 1.
      gravity: 1.
      friction: 1.
  

policy_agent:
  classname: salina_examples.rl.LoP.agents.LoPAgent
  hidden_size: 64
  n_layers: 4
  n_models: ${n_models}
  env:
    classname: ${wrapper_classname}
    env_name: ${env_name}

critic_agent:
  classname: salina_examples.rl.LoP.agents.CriticAgent
  hidden_size: 256
  n_layers: 5
  alpha_size: ${n_models}
  env:
    classname: ${wrapper_classname}
    env_name: ${env_name}

algorithm:
  n_processes: 0
  clip_grad: 10
  update_epochs: 8
  minibatch_size: 512
  num_minibatches: 32
  time_limit: 10000000
  max_epochs: 1501
  discount_factor: 0.99
  clip_ratio: 0.3
  action_std: 0.5
  gae: 0.96
  reward_scaling: 1
  lr_policy: 0.0003
  lr_critic: 0.0003
  beta: 1.
  device: cuda:0
  n_models: ${n_models}
  geometry: simplex
  distribution: categorical

hydra:
  run:
    dir: ./
  launcher:
    mem_gb: 16
    max_num_timeout: 0
    cpus_per_task: 1
    signal_delay_s: 30
    timeout_min: 600
    gpus_per_node: 1
    tasks_per_node: 1
    partition: prioritylab
    comment: ICLR2022
  job_logging:
    root:
      handlers: []

defaults:
  - override hydra/launcher: submitit_slurm